### ISSUE TITLE
Fault Error

### ISSUE THREAD

**Issue by pranid** [enets/enets2-php-sdk#1]
Hi,

I have been getting a fault error on https://uat-api.nets.com.sg:9065/MerchantApp/sim/b2sTxnEndURL.jsp while performing  UAT.

I used BANKSIM which redirected to https://test.enets.sg/enets/banksim/BankSim.jsp.

Please assist.

**Comment by hermansantoso** [comment]
what is the error message? Seems like the error is at enets side. if it is, please escalate to enets support accordingly. Let me know again if it is eventually caused by the library.

This github issue only address the issue on the library itself as this is my personal github page, and I'm not enets staff. thanks.

**Comment by pranid** [comment]
The library works fine. That error was occurred at ENETS side.
